log_level: "debug"
guest_defaults:
  network: "bridge"
paths:
  base_images: "/opt/kvm/cloud-images"
  live_images: "/opt/kvm/live-images"
  live_iso_images: "/opt/kvm/seed-isos"
distros:
  - name: "ubuntu"
    version: "18.10"
    url: "https://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-amd64.img"
    
  - name: "ubuntu"
    version: "18.04"
    url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"

  - name: "ubuntu"
    version: "16.04"
    url: "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img"

  - name: "centos"
    version: "7"
    url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1808.qcow2"

  - name: "centos"
    version: "6"
    url: "https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2"

  - name: "cirros"
    version: "0.4"
    url: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-aarch64-disk.img"

  - name: "amazon"
    version: "2"
    url: "https://cdn.amazonlinux.com/os-images/2.0.20180810/kvm/amzn2-kvm-2.0.20180810-x86_64.xfs.gpt.qcow2"

  - name: "fedora"
    version: "28"
    url: "https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2"

  - name: "debian"
    version: "9"
    url: "https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2"

  - name: "debian"
    version: "8"
    url: "https://cdimage.debian.org/cdimage/openstack/current-8/debian-8-openstack-amd64.qcow2"
